sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t jknighten/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jknighten/react-test npm test -- --coverage


after_success:
  - docker build -t jknighten/multi-client ./client
  - docker build -t jknighten/multi-nginx ./nginx
  - docker build -t jknighten/multi-server ./server
  - docker build -t jknighten/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jknighten/multi-client
  - docker push jknighten/multi-nginx
  - docker push jknighten/multi-server
  - docker push jknighten/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-324597442476'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY